/**
 * Support contact constants.
 *
 * The ONLY support channel on the storefront is WhatsApp — one number
 * shared by customers and vendors. Centralised here so it is never
 * scattered across components.
 *
 * NB: this is intentionally a plain constants file and NOT environment.ts.
 * environment.ts is auto-generated by inject-environment.mjs at build time
 * and would strip any key it doesn't know about, so the number must live
 * outside it.
 */

/** E.164 digits (no '+'), used to build the wa.me deep link. */
export const SUPPORT_WHATSAPP_NUMBER = '971507967776';

/** Human-readable form for display in the UI. */
export const SUPPORT_WHATSAPP_DISPLAY = '+971 50 796 7776';

/**
 * WhatsApp deep link. Opened the same way the existing share/support
 * handlers open it (anchor with target="_blank" rel="noopener").
 * A greeting can be appended via ?text=<encoded> by the caller.
 */
export const SUPPORT_WHATSAPP_URL = `https://wa.me/${SUPPORT_WHATSAPP_NUMBER}`;
