/**
 * Support contact constants.
 *
 * The ONLY support channel for both customers and vendors is WhatsApp,
 * on a single shared number. Keep this centralised, do NOT scatter the
 * raw number across handlers, and do NOT put it in environment.ts (that
 * file is auto-generated by inject-environment.mjs and would strip it).
 */

/** Bare WhatsApp number (no +, no spaces), used to build wa.me deep links. */
export const SUPPORT_WHATSAPP = '971507967776';

/** Human-readable display form of {@link SUPPORT_WHATSAPP}. */
export const SUPPORT_WHATSAPP_DISPLAY = '+971 50 796 7776';

/**
 * Build a wa.me deep link to support, optionally with a pre-filled greeting.
 * Opened the same way existing handlers open it: window.open(url, '_system').
 */
export function supportWhatsappLink(greeting?: string): string {
  const base = `https://wa.me/${SUPPORT_WHATSAPP}`;
  return greeting ? `${base}?text=${encodeURIComponent(greeting)}` : base;
}

/**
 * WhatsApp Business number that reaches Ain (the concierge over WhatsApp,
 * Phase 4). Defaults to the shared support number; point this at a dedicated
 * Meta Cloud API number once one is provisioned + the webhook is wired. An
 * empty string hides the "Chat with Ain on WhatsApp" entry point.
 */
export const AIN_WHATSAPP: string = SUPPORT_WHATSAPP;

/** wa.me deep link to Ain with an optional pre-filled greeting; '' when unset. */
export function ainWhatsappLink(greeting?: string): string {
  if (!AIN_WHATSAPP) {
    return '';
  }
  const base = `https://wa.me/${AIN_WHATSAPP}`;
  return greeting ? `${base}?text=${encodeURIComponent(greeting)}` : base;
}
