/**
 * Support contact constants.
 *
 * The ONLY support channel for both customers and vendors is WhatsApp,
 * on a single shared number. Keep this centralised, do NOT scatter the
 * raw number across handlers, and do NOT put it in environment.ts (that
 * file is auto-generated by inject-environment.mjs and would strip it).
 */

/** Bare WhatsApp number (no +, no spaces), used to build wa.me deep links. */
export const SUPPORT_WHATSAPP = '971507967776';

/** Human-readable display form of {@link SUPPORT_WHATSAPP}. */
export const SUPPORT_WHATSAPP_DISPLAY = '+971 50 796 7776';

/**
 * Build a wa.me deep link to support, optionally with a pre-filled greeting.
 * Opened the same way existing handlers open it: window.open(url, '_system').
 */
export function supportWhatsappLink(greeting?: string): string {
  const base = `https://wa.me/${SUPPORT_WHATSAPP}`;
  return greeting ? `${base}?text=${encodeURIComponent(greeting)}` : base;
}
