import {
  // navigation / chevrons / arrows
  ArrowLeft, ArrowRight, ArrowUp, ArrowDown, ChevronRight, ChevronLeft,
  ChevronDown, ChevronUp, ChevronsUpDown, ChevronFirst, ChevronLast,
  ExternalLink, EllipsisVertical, Ellipsis, Menu, X,
  // actions
  Save, Plus, CirclePlus, Minus, Pencil, Trash2, Copy, Download, Upload,
  Send, RefreshCw, RotateCcw, Undo2, Redo2, Search, SearchX,
  FunnelX, Check, CheckCheck, ListFilter, Columns3, Settings, Tag, Tags,
  Link2, SlidersHorizontal,
  // status / feedback
  CircleCheck, CircleX, Info, Ban, Shield, ShieldCheck,
  BadgeCheck, Circle,
  // commerce
  Store, ShoppingCart, ShoppingBag, Package, ReceiptText,
  Receipt, Truck, CreditCard, Wallet, Gift, BadgePercent, Landmark,
  ArrowRightLeft, FileText,
  // people / account
  User, UserPlus, Users, CircleUserRound, Phone, PhoneCall, Mail, Key,
  Lock, LogOut, ShieldUser,
  // content / formatting
  Bold, Italic, Underline, Strikethrough, Quote, ListOrdered, List,
  Heading1, Heading2, Heading3, Code, Folder, FolderOpen, Grid3x3,
  LayoutGrid, LayoutDashboard, Star, StarHalf, Heart,
  // analytics / misc
  TrendingUp, ChartColumn, ChartLine, Activity, Gauge, Rocket,
  Bell, BellOff, MessageSquare, MessagesSquare, Inbox, Calendar,
  Ruler, FilePen, Megaphone, Dices, Wifi, SignalHigh, BatteryFull,
  Hand, Eye, ClipboardCheck, CornerDownLeft, Flag, House,
  ToggleRight, Headset, type LucideIconData,
} from 'lucide-angular';

/**
 * Maps the legacy Material Symbols names (still used throughout the
 * templates and rowAction configs) to Lucide icon data. Keeping the
 * Material names as the public API means the icon sweep was a pure
 * tag swap, the name→glyph decision lives only here.
 *
 * If a name is missing at runtime the IconComponent falls back to a
 * neutral dot (Circle), so a typo degrades gracefully rather than
 * throwing.
 */
export const ICON_MAP: Record<string, LucideIconData> = {
  // arrows / nav
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  unfold_more: ChevronsUpDown,
  first_page: ChevronFirst,
  last_page: ChevronLast,
  open_in_new: ExternalLink,
  more_vert: EllipsisVertical,
  more_horiz: Ellipsis,
  menu: Menu,
  close: X,
  link: Link2,

  // actions
  save: Save,
  add: Plus,
  add_circle: CirclePlus,
  remove: Minus,
  edit: Pencil,
  delete: Trash2,
  content_copy: Copy,
  download: Download,
  publish: Upload,
  upload_file: Upload,
  send: Send,
  refresh: RefreshCw,
  restart_alt: RotateCcw,
  undo: Undo2,
  redo: Redo2,
  search: Search,
  search_off: SearchX,
  filter_list: ListFilter,
  filter_list_off: FunnelX,
  check: Check,
  done_all: CheckCheck,
  view_column: Columns3,
  tune: SlidersHorizontal,
  settings: Settings,
  label: Tag,
  local_offer: Tag,
  category: Tags,

  // status / feedback
  check_circle: CircleCheck,
  error: CircleX,
  info: Info,
  block: Ban,
  shield: Shield,
  verified_user: ShieldCheck,
  verified: BadgeCheck,
  policy: Shield,
  task_alt: ClipboardCheck,
  radio_button_unchecked: Circle,

  // commerce
  store: Store,
  storefront: Store,
  shop: Store,
  shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  inventory: Package,
  inventory_2: Package,
  receipt_long: ReceiptText,
  receipt: Receipt,
  request_quote: FileText,
  local_shipping: Truck,
  truck: Truck,
  credit_card: CreditCard,
  payments: Wallet,
  card_giftcard: Gift,
  sell: BadgePercent,
  account_balance: Landmark,
  currency_exchange: ArrowRightLeft,

  // people / account
  person: User,
  person_add: UserPlus,
  group: Users,
  people: Users,
  account_circle: CircleUserRound,
  admin_panel_settings: ShieldUser,
  phone: Phone,
  call: PhoneCall,
  mail: Mail,
  mail_outline: Mail,
  email: Mail,
  key: Key,
  lock: Lock,
  logout: LogOut,

  // content / formatting
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_strikethrough: Strikethrough,
  format_quote: Quote,
  format_list_numbered: ListOrdered,
  format_list_bulleted: List,
  list: List,
  format_h1: Heading1,
  format_h2: Heading2,
  format_h3: Heading3,
  code: Code,
  folder: Folder,
  folder_open: FolderOpen,
  grid_view: Grid3x3,
  apps: LayoutGrid,
  dashboard: LayoutDashboard,
  star: Star,
  star_half: StarHalf,
  favorite_border: Heart,

  // analytics / misc
  trending_up: TrendingUp,
  bar_chart: ChartColumn,
  insights: ChartLine,
  analytics: Activity,
  speed: Gauge,
  signal_cellular_alt: SignalHigh,
  battery_5_bar: BatteryFull,
  wifi: Wifi,
  rocket_launch: Rocket,
  notifications: Bell,
  notifications_off: BellOff,
  chat: MessageSquare,
  forum: MessagesSquare,
  reviews: MessageSquare,
  confirmation_number: Receipt,
  inbox: Inbox,
  calendar_today: Calendar,
  straighten: Ruler,
  assignment_return: FilePen,
  keyboard_return: CornerDownLeft,
  campaign: Megaphone,
  casino: Dices,
  waving_hand: Hand,
  visibility: Eye,
  flag: Flag,
  home: House,
  toggle_on: ToggleRight,
  support_agent: Headset,
  cancel: CircleX,
};
