/**
 * AUTO-GENERATED by scripts/inject-environment.mjs at build time.
 *
 * DO NOT EDIT THIS FILE BY HAND. Your changes will be overwritten on the
 * next build. To change values, set environment variables before running
 * the build:
 *   SITE_URL=https://example.com SENTRY_DSN=... GA4_MEASUREMENT_ID=G-... npm run build
 *
 * Source-of-truth env vars are listed in scripts/inject-environment.mjs.
 */

export const environment = {
  SITE_URL: "https://staging.3bayti.ae",
  SENTRY_DSN: "",
  GA4_MEASUREMENT_ID: "",
} as const;
