/**
 * AUTO-GENERATED by scripts/inject-environment.mjs at build time.
 *
 * DO NOT EDIT THIS FILE BY HAND. Your changes will be overwritten on the
 * next build. To change values, set environment variables before running
 * the build:
 *   SITE_URL=https://example.com SENTRY_DSN=... GA4_MEASUREMENT_ID=G-... npm run build
 *
 * Source-of-truth env vars are listed in scripts/inject-environment.mjs.
 */

export const environment = {
  SITE_URL: "https://staging.3bayti.ae",
  SENTRY_DSN: "https://822503d1eda33a1e983a6aa0a8f9dce7@o4511365625872384.ingest.us.sentry.io/4511365627772928",
  GA4_MEASUREMENT_ID: "G-W2YF72TS3F",

  /* Google Places API (New) — powers the street-address autocomplete on the
     checkout/address form (apps/web/src/app/core/places). If apiKey is empty
     the autocomplete degrades gracefully to a plain text input.

     SECURITY: this is currently the same key the mobile app ships. For web it
     SHOULD be replaced with an HTTP-referrer-restricted web key (restricted to
     the 3bayti.ae origins) + a usage quota cap in Google Cloud Console. */
  googlePlaces: {
    apiKey: 'AIzaSyAHERMyCn9KfrhZF5zpKynzLp0SjXpQpKU',
    /* ISO 3166-1 alpha-2 country code(s) to restrict autocomplete to. */
    regions: ['AE'],
  },

  /* Mobile app store listings for the home "Get the app" section. Set
     APP_STORE_URL / PLAY_STORE_URL at build time; '#' renders a
     non-navigating "coming soon" badge. */
  appStores: {
    appStore: "https://apps.apple.com/ar/app/3bayti/id6752422907",
    playStore: "https://play.google.com/store/apps/details?id=com.bayti.app",
  },
} as const;
