<?php

declare(strict_types=1);

namespace Bayti\Api\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M1.1 — initial schema for users, addresses, measurements, refresh
 * tokens, OTP attempts.
 *
 * This is the first migration on the new PostgreSQL platform. It
 * creates the auth-related schema; catalog/cart/order tables come
 * in later migrations (M2 catalog, M3 lifecycle).
 *
 * Conventions
 * -----------
 * - Snake_case column names (matched by Doctrine UnderscoreNamingStrategy)
 * - TIMESTAMPTZ for all timestamps (timezone-aware)
 * - JSONB (not JSON) for the measurements column — supports indexing
 *   and faster equality checks
 * - BIGSERIAL primary keys, prepared for high-volume scenarios
 * - Indexes match the entity's #[ORM\Index] annotations
 *
 * Why hand-written and not generated by 'doctrine migrations:diff'
 * ----------------------------------------------------------------
 * The diff tool needs an existing schema to compare against. On the
 * empty PostgreSQL database, diff produces a usable but messy
 * migration that lacks comments and uses SchemaTool's mechanical
 * column ordering. This file is hand-written for clarity and
 * carefully ordered (FKs reference tables in dependency order).
 *
 * Future migrations can use diff + manual cleanup; this first one
 * sets the precedent for how new tables look.
 */
final class Version20260507000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'M1.1: initial schema (users, addresses, measurements, refresh_tokens, otp_attempts)';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'This migration only supports PostgreSQL.'
        );

        // -----------------------------------------------------------
        // users
        // -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE users (
                id BIGSERIAL PRIMARY KEY,
                legacy_user_id INTEGER UNIQUE,

                first_name VARCHAR(100),
                last_name VARCHAR(100),
                email VARCHAR(255) NOT NULL UNIQUE,
                phone VARCHAR(25) NOT NULL UNIQUE,
                country_code VARCHAR(2) NOT NULL DEFAULT 'AE',

                password_hash VARCHAR(255) NOT NULL,
                password_changed_at TIMESTAMPTZ,

                store_legal_name VARCHAR(255),
                trade_license_number VARCHAR(100),

                is_customer BOOLEAN NOT NULL DEFAULT TRUE,
                is_vendor BOOLEAN NOT NULL DEFAULT FALSE,
                is_admin BOOLEAN NOT NULL DEFAULT FALSE,
                is_finance BOOLEAN NOT NULL DEFAULT FALSE,
                is_support BOOLEAN NOT NULL DEFAULT FALSE,
                is_sub_admin BOOLEAN NOT NULL DEFAULT FALSE,

                is_store_approved BOOLEAN NOT NULL DEFAULT FALSE,
                is_store_active BOOLEAN NOT NULL DEFAULT FALSE,

                is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
                is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                is_2fa BOOLEAN NOT NULL DEFAULT FALSE,

                last_login_at TIMESTAMPTZ,
                last_login_ip VARCHAR(45),
                deleted_at TIMESTAMPTZ,

                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            )
        SQL);

        $this->addSql('CREATE INDEX idx_users_email ON users (email)');
        $this->addSql('CREATE INDEX idx_users_phone ON users (phone)');
        $this->addSql('CREATE INDEX idx_users_legacy_id ON users (legacy_user_id)');
        $this->addSql('CREATE INDEX idx_users_active ON users (is_active) WHERE deleted_at IS NULL');

        // -----------------------------------------------------------
        // addresses
        // -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE addresses (
                id BIGSERIAL PRIMARY KEY,
                legacy_address_id INTEGER UNIQUE,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

                label VARCHAR(50),
                recipient_name VARCHAR(200) NOT NULL,
                recipient_phone VARCHAR(25) NOT NULL,

                emirate VARCHAR(50) NOT NULL,
                area VARCHAR(100) NOT NULL,
                street_address VARCHAR(255),
                building_details TEXT,
                postal_code VARCHAR(20),
                country VARCHAR(2) NOT NULL DEFAULT 'AE',

                is_default_shipping BOOLEAN NOT NULL DEFAULT FALSE,
                is_default_billing BOOLEAN NOT NULL DEFAULT FALSE,

                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            )
        SQL);

        $this->addSql('CREATE INDEX idx_addresses_user ON addresses (user_id)');
        $this->addSql('CREATE INDEX idx_addresses_legacy_id ON addresses (legacy_address_id)');

        // Partial unique indexes — at most one default per user, but
        // the default doesn't have to exist (so a partial unique
        // covers both cases without forcing every user to have one).
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uq_addresses_one_default_shipping
            ON addresses (user_id) WHERE is_default_shipping = TRUE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uq_addresses_one_default_billing
            ON addresses (user_id) WHERE is_default_billing = TRUE
        SQL);

        // -----------------------------------------------------------
        // measurements
        // -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE measurements (
                id BIGSERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

                category_id BIGINT,

                values JSONB NOT NULL DEFAULT '{}'::jsonb,
                notes TEXT,

                created_at TIMESTAMPTZ NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL
            )
        SQL);

        $this->addSql('CREATE INDEX idx_measurements_user ON measurements (user_id)');

        // Composite unique: one row per user per category. Without
        // this, the user could end up with multiple "default"
        // measurement rows, breaking findDefaultForUser().
        // Partial coalesce-unique because (user_id, NULL) needs
        // to also be unique and Postgres treats NULL as never-equal.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uq_measurements_user_category
            ON measurements (user_id, COALESCE(category_id, 0))
        SQL);

        // -----------------------------------------------------------
        // user_refresh_tokens
        // -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE user_refresh_tokens (
                id BIGSERIAL PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

                jti VARCHAR(36) NOT NULL UNIQUE,
                token_hash VARCHAR(64) NOT NULL,

                issued_at TIMESTAMPTZ NOT NULL,
                expires_at TIMESTAMPTZ NOT NULL,
                revoked_at TIMESTAMPTZ,
                revoked_reason VARCHAR(30),

                issued_ip VARCHAR(45),
                user_agent VARCHAR(500)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_refresh_tokens_user ON user_refresh_tokens (user_id)');
        $this->addSql('CREATE INDEX idx_refresh_tokens_jti ON user_refresh_tokens (jti)');
        $this->addSql('CREATE INDEX idx_refresh_tokens_expiry ON user_refresh_tokens (expires_at)');

        // Index for the active-sessions query (user_id + revoked IS NULL + expires > now).
        // Partial index since we mostly query for active tokens.
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_refresh_tokens_active
            ON user_refresh_tokens (user_id, expires_at)
            WHERE revoked_at IS NULL
        SQL);

        // -----------------------------------------------------------
        // user_otp_attempts
        //
        // We don't store the actual 6-digit code or per-attempt
        // verify counters here — MessageCentral CPaaS handles code
        // generation and verification on their side. We store only
        // the verificationId they return + audit context.
        // -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE user_otp_attempts (
                id BIGSERIAL PRIMARY KEY,
                user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,

                verification_id VARCHAR(100) NOT NULL UNIQUE,
                phone VARCHAR(25) NOT NULL,
                purpose VARCHAR(30) NOT NULL,

                created_at TIMESTAMPTZ NOT NULL,
                expires_at TIMESTAMPTZ NOT NULL,
                consumed_at TIMESTAMPTZ,

                requested_ip VARCHAR(45)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_otp_attempts_phone ON user_otp_attempts (phone)');
        $this->addSql('CREATE INDEX idx_otp_attempts_user ON user_otp_attempts (user_id)');
        $this->addSql('CREATE INDEX idx_otp_attempts_expiry ON user_otp_attempts (expires_at)');

        // Note: verification_id has an implicit unique index from the
        // UNIQUE constraint above; findByVerificationId uses that.

        // For rate-limit queries (recent sends per phone).
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_otp_attempts_phone_created
            ON user_otp_attempts (phone, created_at DESC)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // Drop in reverse order of creation. CASCADE not needed
        // because we drop the dependent tables first.
        $this->addSql('DROP TABLE IF EXISTS user_otp_attempts');
        $this->addSql('DROP TABLE IF EXISTS user_refresh_tokens');
        $this->addSql('DROP TABLE IF EXISTS measurements');
        $this->addSql('DROP TABLE IF EXISTS addresses');
        $this->addSql('DROP TABLE IF EXISTS users');
    }
}
