<?php

declare(strict_types=1);

namespace Bayti\Api\Migration;

/**
 * Generates URL-safe slugs from arbitrary text, with collision tracking.
 *
 * Used during migration because legacy vendors all have empty store_slug
 * (9311 of 9311 are NULL), and legacy products have NO slug column at
 * all. We generate slugs from names, and resolve collisions by appending
 * `-2`, `-3`, etc.
 *
 * Usage:
 *   $slugger = new Slugger();
 *   $slug1 = $slugger->make('Almas Fashion');     // 'almas-fashion'
 *   $slug2 = $slugger->make('Almas Fashion');     // 'almas-fashion-2'
 *   $slug3 = $slugger->make('Almas Fashion!');    // 'almas-fashion-3'
 *
 * The slugger maintains its own in-memory used-set per instance so all
 * slugs generated by ONE migration run are unique against each other.
 * Callers pass `reserve()` for pre-existing DB slugs they want to avoid
 * (e.g. seed data we don't roll back).
 *
 * Unicode handling: stripped to ASCII. Arabic names → use `iconv` with
 * TRANSLIT to attempt approximation, fallback to numeric suffix only
 * if the slug becomes empty.
 */
final class Slugger
{
    /** @var array<string, bool> Slugs already in use. */
    private array $used = [];

    /**
     * Mark a slug as already-used (e.g. from pre-existing DB rows).
     */
    public function reserve(string $slug): void
    {
        $this->used[$slug] = true;
    }

    /**
     * Generate a unique slug from the given source string. Appends
     * a numeric suffix on collision.
     *
     * Returns null only if source is empty AND fallback is null
     * (caller should provide a fallback like the legacy id).
     */
    public function make(string $source, ?string $fallback = null): ?string
    {
        $base = $this->normalize($source);
        if ($base === '' && $fallback !== null) {
            $base = $this->normalize($fallback);
        }
        if ($base === '') {
            return null;
        }

        // Trim to max 100 chars BEFORE collision suffix so the suffix
        // never gets cut off.
        if (strlen($base) > 95) {
            $base = substr($base, 0, 95);
            $base = rtrim($base, '-');
        }

        $candidate = $base;
        $suffix = 2;
        while (isset($this->used[$candidate])) {
            $candidate = $base . '-' . $suffix;
            $suffix++;
            if ($suffix > 10000) {
                // Should never happen; protect against runaway loop.
                return null;
            }
        }

        $this->used[$candidate] = true;
        return $candidate;
    }

    /**
     * Convert arbitrary text to kebab-case ASCII.
     *
     * Pipeline:
     *   1. iconv transliterate (Arabic → ASCII approximation, accents → base letter)
     *   2. lowercase
     *   3. anything not [a-z0-9] → '-'
     *   4. collapse repeated '-' and trim
     */
    private function normalize(string $source): string
    {
        $source = trim($source);
        if ($source === '') {
            return '';
        }

        // iconv may throw on invalid UTF-8; suppress + fallback.
        $ascii = @iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $source);
        if ($ascii === false || $ascii === '') {
            // For pure-Arabic strings, iconv may return nothing useful.
            // Fall through to direct preg_replace which will just strip
            // non-ASCII; caller fallback (e.g. legacy id) will save us.
            $ascii = $source;
        }

        $ascii = strtolower($ascii);
        $ascii = preg_replace('/[^a-z0-9]+/', '-', $ascii) ?? '';
        $ascii = trim($ascii, '-');
        return $ascii;
    }
}
